version: '2'

services:
  db:
    image: suseru/mariadb:10.8.3
    environment:
      - MYSQL_INITDB_SKIP_TZINFO=1
    restart: always
    volumes:
      - ./mariadb:/var/lib/mysql
    extends:
      service: base
      file: docker-compose-base.yml

  rmt:
    image: suseru/rmt-airgap:2.9
    environment:
      - RMT_REMOTE_HOST=${RMT_REMOTE_HOST}
      - RSYNC_USER=${RSYNC_USER}
      - USER_PASS=${USER_PASS}
      - MYSQL_HOST=db
      - MYSQL_DATABASE=rmt
      - MYSQL_USER=rmt
      - MYSQL_PASSWORD=rmt
      - MYSQL_PWD=toor
      - MYSQL_ROOT_PASSWORD=toor
      - SCC_USERNAME=${SCC_USERNAME}
      - SCC_PASSWORD=${SCC_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ./public:/var/lib/rmt/public
      - ./rmt-start.sh:/usr/local/bin/rmt-start.sh
      - ./keys:/root/.ssh
    depends_on:
      - db
    entrypoint: /bin/bash /usr/local/bin/rmt-start.sh

  nginx:
    image: suseru/nginx:1.23.1
    volumes:
      - ./public:/usr/share/rmt/public
      - ./ssl:/etc/rmt/ssl
      - ./nginx/rmt-server-http.conf:/etc/nginx/vhosts.d/rmt-server-http.conf
      - ./nginx/rmt-server-https.conf:/etc/nginx/vhosts.d/rmt-server-https.conf
    ports:
      - "${EXTERNAL_PORT_HTTP}:80"
      - "${EXTERNAL_PORT_HTTPS}:443"
    depends_on:
      - rmt
